// <auto-generated />
namespace StockSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addtbls111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtbls111));
        
        string IMigrationMetadata.Id
        {
            get { return "202012281544053_addtbls111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
